### ISSUE TITLE
Logger cleanup

### ISSUE THREAD

**Issue by mharj** [iwanbk/nyamuk#2]
<pre>
class Nyamuk(base_nyamuk.BaseNyamuk):
    def __del__(self):
        self.logger.handlers=[]
</pre>
or even delete logger to cleanup logs when deleting class itself.
This is visible when connection fails and make new instance of class which gets old log data and each connection failure adds content to log.

**Comment by gbour** [comment]
closing this issue as the MR was merged long time ago
