### ISSUE TITLE
pip install for v0.2.0 fails with "IOError: [Errno 2] No such file or directory: 'README'"

### ISSUE THREAD

**Issue by jdanekrh** [iwanbk/nyamuk#20]
$ pip install https://github.com/iwanbk/nyamuk/archive/v0.2.0.zip
    Collecting https://github.com/iwanbk/nyamuk/archive/v0.2.0.zip
    Downloading https://github.com/iwanbk/nyamuk/archive/v0.2.0.zip
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-9ZSylS-build/setup.py", line 4, in <module>
            long_description = open('README').read()
        IOError: [Errno 2] No such file or directory: 'README'

Apparently, the `README` file was renamed to `README.md` and `setup.py` was not updated.

**Comment by gbour** [comment]
fixed
