### ISSUE TITLE
in handle_publish     message.msg.topic = ba_data.decode('utf8')

### ISSUE THREAD

**Issue by Cyrus-Coinkeeper** [iwanbk/nyamuk#22]
Subscriber recive payload head is 0x31 and  [ret=2, ba_data=None] while too much publish
error:
File "D:\python_pj\testpy\nyamuk\nyamuk.py", line 401, in handle_publish
    message.msg.topic = ba_data.decode('utf8')
AttributeError: 'NoneType' object has no attribute 'decode'

what can i do ?

**Comment by iwanbk** [comment]
@jhonkingcai 
Can you give more details about your issue? Maybe your test scenario

**Comment by gbour** [comment]
As @iwanbk said, it's hard to debug without some kind of network trace, test case or code sample.
As I understand your message, the received packet header is 0x31, which correspond to a **CONNECT** message, not a **PUBLISH** one

You do you decode the packet: are you calling _packet_handle()_ function or directly _handle_publish()_ ?

**Comment by gbour** [comment]
I close this issue as @jhonkingcai did not answered.
